version: '3.7'

services:
  broker-service:
    build:
      context: .
      dockerfile: ./docker/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
